name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Configure AWS credentials using OIDC (no static keys)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{GITHUB_OIDC_ROLE_NAME}}
          aws-region: {{AWS_REGION}}

      # 2) Fetch Sonar token from AWS Secrets Manager
      - name: Get Sonar token from AWS Secrets Manager
        id: sonar_secret
        run: |
          SONAR_TOKEN=$(aws secretsmanager get-secret-value \
            --secret-id {{SONAR_SECRET_NAME}} \
            --query SecretString --output text)
          echo "token-retrieved=true" >> $GITHUB_OUTPUT
          echo "::add-mask::$SONAR_TOKEN"
          echo "SONAR_TOKEN=$SONAR_TOKEN" >> $GITHUB_ENV

      # 3) Setup Node (for scanner prerequisites)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4) SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          projectBaseDir: .
